title: fedex_account_settings_request_body
type: object
properties:
  nickname:
    type: string
  pickup_type:
    $ref: '../enums.yaml#/fedex_pickup_type'
  smart_post_hub:
    $ref: '../enums.yaml#/smart_post_hub'
  smart_post_endorsement:
    $ref: '../enums.yaml#/smart_post_endorsement'
  is_primary_account:
    type: boolean
