title: service
type: object
properties:
  carrier_id:
    allOf:
      - $ref: 'primitives.yaml#/se_id'
    description: A string that uniquely identifies the carrier id
  carrier_code:
    type: string
  service_code:
    type: string
  name:
    type: string
  domestic:
    type: boolean
  international:
    type: boolean
  is_multi_package_supported:
    type: boolean
