title: ups_account_settings
type: object
additionalProperties: false
properties:
  nickname:
    type: string
  is_primary_account:
    type: boolean
  pickup_type:
    $ref: 'enums.yaml#/ups_pickup_type'
  use_carbon_neutral_shipping_program:
    type: boolean
  use_ground_freight_pricing:
    type: boolean
  use_consolidation_services:
    type: boolean
  use_order_number_on_mail_innovations_labels:
    type: boolean
  mail_innovations_endorsement:
    $ref: 'enums.yaml#/mail_innovations_endorsement'
  mail_innovations_cost_center:
    type: string
  use_negotiated_rates:
    type: boolean
  account_postal_code:
    type: string
  invoice:
    additionalProperties: false
    allOf:
      - $ref: ups_invoice.yaml
